spring:
  main:
    web-application-type: none
  profiles:
    include: redis


zookeeper:
  connect:
    url: localhost:2111
    SessionTimeout: 600000

logging:
  config: classpath:logback-spring.xml

node:
  ip: 127.0.0.1
  port: 9998