spring:
  main:
    web-application-type: none
  profiles:
    include: redis


zookeeper:
  connect:
    url: localhost:2111
    SessionTimeout: 600000

node:
  ip: 192.168.56.1
  port: 9999

logging:
  config: classpath:log4j2.xml
